stages:
  prepare:
    cmd: "python src/prepare.py data/raw/iris.csv"
    deps:
    - data/raw/iris.csv
    - src/prepare.py
    params:
    - prepare.seed
    - prepare.split
    outs:
    - data/prepared

  train:
    cmd: python src/train.py data/prepared model.pkl
    deps:
    - data/prepared
    - data/prepared/X_train.csv
    - data/prepared/y_train.csv
    - data/prepared/X_test.csv
    - data/prepared/y_test.csv
    - src/train.py
    params:
    - train.seed
    outs:
    - model.pkl
    metrics:
      - metrics.json
